variables:
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
  AWS_ACCOUNT_ID: $AWS_ACCOUNT_ID
  IMAGE_NAME: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/juice-shop

stages:
  - cache
  - test
  - build
  - upload-reports
  - deploy


deploy_image:
  stage: deploy
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  script:
    - COMMAND_ID=$(aws ssm send-command --instance-ids "i-00fef952b853e73b9" --document-name "AWS-RunShellScript" --parameters 'commands=["echo HelloWorld"]' --query "Command.CommandId" --output text)
    - aws ssm get-command-invocation --command-id "$COMMAND_ID" --instance-id "i-00fef952b853e73b9"
