name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - feature/09.04-ssm

env:
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  IMAGE_NAME: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com/juice-shop

jobs:
  deploy_image:
    runs-on: ubuntu-latest
    container:
      image: amazon/aws-cli:latest
    steps:
      - name: Install tar and gzip utilities
        run: |
          yum update -y
          yum install -y tar gzip

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Deploy image using AWS SSM
        run: |
          LOG_IN_CMD="export AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }}; aws ecr get-login-password | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com"
          COMMANDS_TO_EXECUTE="docker pull $IMAGE_NAME:latest && (docker stop juice-shop || true) && (docker rm juice-shop || true) && docker run -d --name juice-shop -p 3000:3000 $IMAGE_NAME:latest"
          FULL_COMMAND="export AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }}; aws ecr get-login-password | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com; docker pull $IMAGE_NAME:latest && (docker stop juice-shop || true) && (docker rm juice-shop || true) && docker run -d --name juice-shop -p 3000:3000 $IMAGE_NAME:latest"
          
          COMMAND_ID=$(aws ssm send-command \
            --instance-ids "i-0e8a8b5490aa5a8de" \
            --document-name "AWS-RunShellScript" \
            --parameters commands=["${FULL_COMMAND}"] \
            --query "Command.CommandId" \
            --output text)
          
          echo "Command ID: $COMMAND_ID"
          
          aws ssm get-command-invocation --command-id "$COMMAND_ID" --instance-id "i-0e8a8b5490aa5a8de"

      - name: Send HelloWorld command using AWS SSM
        run: |
          aws ssm send-command \
            --instance-ids "i-0e8a8b5490aa5a8de" \
            --document-name "AWS-RunShellScript" \
            --parameters "commands=['echo HelloWorld']"


